var hash = {}, key1={}, key2=[];
hash[1] = "Uno (number)";
hash["juan"] = "John";
hash[key1]="Key 1 value";
hash[key2]="Key 2 value";
console.log(hash[1]);
console.log(hash["juan"]);
console.log(hash[key1]);
console.log(hash[key2]);
var key3={name:"juan"}, key4=["juan"];
hash["1"] = "Uno (string)";
hash[key3]="Mary";
hash[key4]="Beth";
console.log(hash["1"]);
console.log(hash[1]);
console.log(hash[key3]);
console.log(hash[key1]);
console.log(hash[key4]);
console.log(hash["juan"]);
